let &t_si = "\e[6 q"   " insert mode: vertical bar
let &t_ei = "\e[2 q"   " normal mode: block

set nocompatible

filetype on
filetype plugin on
filetype indent on

syntax on

set number
set relativenumber
set shiftwidth=4
set tabstop=4
set expandtab
set nobackup
set scrolloff=10
set nowrap
set incsearch
set ignorecase
set smartcase
set showcmd
set showmode
set showmatch
set hlsearch
set history=1000
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

colorscheme retrobox
